CREATE TABLE EDGE (
  WEIGHT INT,
  SRC	 INT,
  DST    INT
) IN ADBUTBL01 CHUNK=128 STORAGE FORMAT COLUMN;

CREATE INDEX EDGE_RNG1 ON EDGE (SRC) IN ADBUIDX01 EMPTY INDEXTYPE RANGE;
CREATE INDEX EDGE_RNG2 ON EDGE (DST) IN ADBUIDX01 EMPTY INDEXTYPE RANGE;